blank_issues_enabled: false
contact_links:
  - name: "📬 Soporte directo"
    url: "http://wa.me/+51949033237?text=Hola%2C%20necesito%20ayuda%20con%20el%20proceso%20de%20adopci%C3%B3n"
    about: "¿Necesitas ayuda con el proceso de adopción o no sabes cómo completar el formulario? Escríbenos aquí y con gusto te asistimos."
    